name: platform_maps_flutter
description: A Flutter package that combines google_maps and apple_maps to provide a crossplatform native map implementation.
version: 1.0.2
publish_to: none
#homepage: https://github.com/LuisThein
#repository: https://github.com/LuisThein/platform_maps_flutter
#issue_tracker: https://github.com/LuisThein/platform_maps_flutter/issues

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_maps_flutter: ^2.4.0
  google_maps_flutter_platform_interface: ^2.4.0
  apple_maps_flutter:
    git:
      url: https://github.com/Anjula/apple_maps_flutter.git
      ref: cb853b3f3b86b3453559bf35f632696bb0357234

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
